export const LANGUAGES = [
    { code: 'auto', zh: '自动检测', en: 'Auto Detect', pinyin: 'zidongjiance', isSourceOnly: true },
    { code: 'zh-CN', zh: '简体中文', en: 'Chinese (Simplified)', pinyin: 'jiantizhongwen' },
    { code: 'zh-TW', zh: '繁体中文', en: 'Chinese (Traditional)', pinyin: 'fantizhongwen' },
    { code: 'en', zh: '英语', en: 'English', pinyin: 'yingyu' },
    { code: 'ja', zh: '日语', en: 'Japanese', pinyin: 'riyu' },
    { code: 'ko', zh: '韩语', en: 'Korean', pinyin: 'hanyu' },
    { code: 'fr', zh: '法语', en: 'French', pinyin: 'fayu' },
    { code: 'de', zh: '德语', en: 'German', pinyin: 'deyu' },
    { code: 'es', zh: '西班牙语', en: 'Spanish', pinyin: 'xibanyayu' },
    { code: 'it', zh: '意大利语', en: 'Italian', pinyin: 'yidaliyu' },
    { code: 'ru', zh: '俄语', en: 'Russian', pinyin: 'eyu' },
    { code: 'pt', zh: '葡萄牙语', en: 'Portuguese', pinyin: 'putaoyayu' },
    { code: 'nl', zh: '荷兰语', en: 'Dutch', pinyin: 'helanyu' },
    { code: 'pl', zh: '波兰语', en: 'Polish', pinyin: 'bolanyu' },
    { code: 'ar', zh: '阿拉伯语', en: 'Arabic', pinyin: 'alaboyu' },
    { code: 'hi', zh: '印地语', en: 'Hindi', pinyin: 'yindiyu' },
    { code: 'tr', zh: '土耳其语', en: 'Turkish', pinyin: 'tuerqiyu' },
    { code: 'th', zh: '泰语', en: 'Thai', pinyin: 'taiyu' },
    { code: 'vi', zh: '越南语', en: 'Vietnamese', pinyin: 'yuenanyu' },
    { code: 'id', zh: '印尼语', en: 'Indonesian', pinyin: 'yinniyu' },
    { code: 'ms', zh: '马来语', en: 'Malay', pinyin: 'malaiyu' },
    { code: 'tl', zh: '菲律宾语', en: 'Filipino', pinyin: 'feilubinyu' },
    { code: 'bn', zh: '孟加拉语', en: 'Bengali', pinyin: 'mengjialayu' },
    { code: 'fa', zh: '波斯语', en: 'Persian', pinyin: 'bosiyu' },
    { code: 'he', zh: '希伯来语', en: 'Hebrew', pinyin: 'xibolaiyu' },
    { code: 'sv', zh: '瑞典语', en: 'Swedish', pinyin: 'ruidianyu' },
    { code: 'da', zh: '丹麦语', en: 'Danish', pinyin: 'danmaiyu' },
    { code: 'fi', zh: '芬兰语', en: 'Finnish', pinyin: 'fenlanyu' },
    { code: 'no', zh: '挪威语', en: 'Norwegian', pinyin: 'nuoweiyu' },
    { code: 'cs', zh: '捷克语', en: 'Czech', pinyin: 'jiekeyu' },
    { code: 'hu', zh: '匈牙利语', en: 'Hungarian', pinyin: 'xiongyaliyu' },
    { code: 'el', zh: '希腊语', en: 'Greek', pinyin: 'xilayu' },
    { code: 'ro', zh: '罗马尼亚语', en: 'Romanian', pinyin: 'luomaniyayu' },
    { code: 'uk', zh: '乌克兰语', en: 'Ukrainian', pinyin: 'wukelanyu' },
    { code: 'bg', zh: '保加利亚语', en: 'Bulgarian', pinyin: 'baojialiyayu' },
    { code: 'hr', zh: '克罗地亚语', en: 'Croatian', pinyin: 'keluodiyayu' },
    { code: 'sr', zh: '塞尔维亚语', en: 'Serbian', pinyin: 'saierweiyayu' },
    { code: 'sk', zh: '斯洛伐克语', en: 'Slovak', pinyin: 'siluofakeyu' },
    { code: 'sl', zh: '斯洛文尼亚语', en: 'Slovenian', pinyin: 'siluowenniyayu' },
    { code: 'et', zh: '爱沙尼亚语', en: 'Estonian', pinyin: 'aishaniyayu' },
    { code: 'lv', zh: '拉脱维亚语', en: 'Latvian', pinyin: 'latuoweiyayu' },
    { code: 'lt', zh: '立陶宛语', en: 'Lithuanian', pinyin: 'litaowanyu' },
    { code: 'ga', zh: '爱尔兰语', en: 'Irish', pinyin: 'aierlanyu' },
    { code: 'is', zh: '冰岛语', en: 'Icelandic', pinyin: 'bingdaoyu' },
    { code: 'sq', zh: '阿尔巴尼亚语', en: 'Albanian', pinyin: 'aerbaniyayu' },
    { code: 'mk', zh: '马其顿语', en: 'Macedonian', pinyin: 'maqidunyu' },
    { code: 'mt', zh: '马耳他语', en: 'Maltese', pinyin: 'maertayu' },
    { code: 'cy', zh: '威尔士语', en: 'Welsh', pinyin: 'weiershiyu' },
    { code: 'sw', zh: '斯瓦希里语', en: 'Swahili', pinyin: 'siwaxiliyu' },
    { code: 'af', zh: '南非荷兰语', en: 'Afrikaans', pinyin: 'nanfeihelanyu' }
];